services:
  - docker

before_install:
- cp freesound/local_settings.example.py freesound/local_settings.py
- sed -i 's$^DISPLAY_DEBUG_TOOLBAR.*$DISPLAY_DEBUG_TOOLBAR = False$' freesound/local_settings.py
- make -C docker
- docker-compose build db web

script:
- docker-compose run --rm web python manage.py test --noinput --settings=freesound.test_settings

notifications:
  slack:
    secure: aVyN2TqUMPbHJ4gmp2U/NEZC2rom5KZvvd3YCvcxlNt9ec/r4RlnHM2R+U0SV1aMhz3qmtlol20TEMPVgp9jWN/PTp6/6ryr6v30CEAczEoWwYvvMEX4+juqAn5lQrOujmsTwyyOB9mxHi19rYJd9g9gdekerp242lZ8yBdt3c4=
