version: "3.7"

services:
    tagrecommendation:
        build: .
        init: true
        command: python tagrecommendation_server.py
        volumes:
            - .:/code
            - ../freesound-data/tag_recommendation_models:/tag_recommendation_models
        ports:
            - "8010:8010"
